name:                test
version:             0.1.0.0
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

dependencies:
- base >= 4.7 && < 5
- HUnit

library:
  source-dirs: .
  exposed-modules:
    - DoOp
  ghc-options:
    - -Wall

tests:
  unit-tests:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - HUnit
    - silently
    - test
